services:
  postgresql:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: stefanini
      POSTGRES_USER: stefanini
      POSTGRES_PASSWORD: stefanini_password
      POSTGRES_ROOT_PASSWORD: stefanini_password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data